export const actionTypes = {
    COUNTER_INCREASE: 'COUNTER_INCREASE',
    COUNTER_DECREASE: 'COUNTER_DECREASE',
    COUNTER_INCREASE_BY_TEN: 'COUNTER_INCREASE_BY_TEN',
    COUNTER_DECREASE_BY_TEN: 'COUNTER_DECREASE_BY_TEN',

    REQUEST_JSON_DATA: 'REQUEST_JSON_DATA',
    RECEIVE_JSON_DATA: 'RECEIVE_JSON_DATA',

    START_TIMER_UP: 'START_TIMER_UP',
    START_TIMER_DOWN: 'START_TIMER_DOWN',
    START_TIMER_STOP: 'START_TIMER_STOP'

};